Use relative path to Unicorn config file
Using an absolute path we get the following error

```
donalo@staging:/var/www/donalo/current$ /home/donalo/.rbenv/bin/rbenv exec bundle exec unicorn -c /var/www/donalo/current/config/unicorn.rb -E staging -D
bundler: failed to load command: unicorn (/var/www/donalo/releases/20191216195017Z/vendor/bundle/ruby/2.6.0/bin/unicorn)
ArgumentError: rackup file (config.ru) not readable
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/lib/unicorn/configurator.rb:713:in `parse_rackup_file'
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/lib/unicorn/configurator.rb:86:in `reload'
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/lib/unicorn/configurator.rb:77:in `initialize'
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:79:in `new'
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:79:in `initialize'
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/bin/unicorn:128:in `new'
  /var/www/donalo/shared/vendor/bundle/ruby/2.6.0/gems/unicorn-5.5.1/bin/unicorn:128:in `<top (required)>'
  /var/www/donalo/releases/20191216195017Z/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `load'
  /var/www/donalo/releases/20191216195017Z/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `<top (required)>'
master failed to start, check stderr log for details
```

I don't really see why the `donalo` user has no actual read permissions
in that case above.