Create infrastructure in Hetzner from Ansible
This requires us to create a Donalo project in our Hetzner Cloud account
and create an API token to use from Ansible.

I'm following the docs at
https://docs.ansible.com/ansible/latest/modules/hcloud_server_module.html
but without any luck. The issue I'm having is that the first I specify
gets created successfully but the second one fails with the following
backtrace:

```
Traceback (most recent call last):
  File "/home/pau/.ansible/tmp/ansible-tmp-1573726332.1006827-128831943935521/AnsiballZ_hcloud_server.py", line 102, in <module>
    _ansiballz_main()
  File "/home/pau/.ansible/tmp/ansible-tmp-1573726332.1006827-128831943935521/AnsiballZ_hcloud_server.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/pau/.ansible/tmp/ansible-tmp-1573726332.1006827-128831943935521/AnsiballZ_hcloud_server.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.hcloud.hcloud_server', init_globals=None, run_name='__main__', alter_sys=False)
  File "/home/pau/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/pau/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py", line 500, in <module>
  File "/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py", line 481, in main
  File "/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py", line 431, in present_server
  File "/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py", line 323, in _create_server
  File "/home/pau/.pyenv/versions/donalo/lib/python3.7/site-packages/hcloud/servers/client.py", line 449, in create
    response = self._client.request(url="/servers", method="POST", json=data)
  File "/home/pau/.pyenv/versions/donalo/lib/python3.7/site-packages/hcloud/hcloud.py", line 192, in request
    self._raise_exception_from_json_content(json_content)
  File "/home/pau/.pyenv/versions/donalo/lib/python3.7/site-packages/hcloud/hcloud.py", line 156, in _raise_exception_from_json_content
    details=json_content['error']['details']
hcloud.hcloud.APIException: server limit exceeded

failed: [localhost] (item={'name': 'db', 'server_type': 'cx21', 'image': 'ubuntu-18.04', 'state': 'present'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "image": "ubuntu-18.04",
        "name": "db",
        "server_type": "cx21",
        "state": "present"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/pau/.ansible/tmp/ansible-tmp-1573726332.1006827-128831943935521/AnsiballZ_hcloud_server.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/pau/.ansible/tmp/ansible-tmp-1573726332.1006827-128831943935521/AnsiballZ_hcloud_server.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pau/.ansible/tmp/ansible-tmp-1573726332.1006827-128831943935521/AnsiballZ_hcloud_server.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.hcloud.hcloud_server', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/home/pau/.pyenv/versions/3.7.4/lib/python3.7/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/home/pau/.pyenv/versions/3.7.4/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py\", line 500, in <module>\n  File \"/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py\", line 481, in main\n  File \"/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py\", line 431, in present_server\n  File \"/tmp/ansible_hcloud_server_payload_lyvpjfxy/ansible_hcloud_server_payload.zip/ansible/modules/cloud/hcloud/hcloud_server.py\", line 323, in _create_server\n  File \"/home/pau/.pyenv/versions/donalo/lib/python3.7/site-packages/hcloud/servers/client.py\", line 449, in create\n    response = self._client.request(url=\"/servers\", method=\"POST\", json=data)\n  File \"/home/pau/.pyenv/versions/donalo/lib/python3.7/site-packages/hcloud/hcloud.py\", line 192, in request\n    self._raise_exception_from_json_content(json_content)\n  File \"/home/pau/.pyenv/versions/donalo/lib/python3.7/site-packages/hcloud/hcloud.py\", line 156, in _raise_exception_from_json_content\n    details=json_content['error']['details']\nhcloud.hcloud.APIException: server limit exceeded\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

I guessed it was due to the fact that I was specifying the `datacenter`.
Then I tried with just `location` and no luck either. Now without even
that parameter it still fails.

Note that no matter which server I define first (db or app) the second
one on the list always fails.